theme: jekyll-theme-slate
title: ![logo](https://raw.githubusercontent.com/insta4fools/insta4fools.github.io/master/i4f_crop.png) Insta4Fools
description: Powerful Instagram bot
github.is_project_page: false
